### ISSUE TITLE
Startet nicht

### ISSUE THREAD

**Issue by gamedown0091** [AtomSponge/Hosencorp#72]
der Launcher schließt sich kurz kommt aber daraufhin wieder.
Log:
[B#211] Running javaw.exe -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:MaxPermSize=256m -Djava.library.path=C:\Users\l.michael\AppData\Roaming\.technic\modpacks\hosencorp-official\bin\natives -Dfml.core.libraries.mirror=http://mirror.technicpack.net/Technic/lib/fml/%s -Dminecraft.applet.TargetDirectory=C:\Users\l.michael\AppData\Roaming\.technic\modpacks\hosencorp-official -cp C:\Users\l.michael\AppData\Roaming\.technic\cache\net\minecraft\launchwrapper\1.8\launchwrapper-1.8.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\ow2\asm\asm-all\4.1\asm-all-4.1.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\scala-lang\scala-library\2.10.2\scala-library-2.10.2.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\scala-lang\scala-compiler\2.10.2\scala-compiler-2.10.2.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\argo\argo\2.25_fixed\argo-2.25_fixed.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\bouncycastle\bcprov-jdk15on\1.47\bcprov-jdk15on-1.47.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\google\guava\guava\14.0\guava-14.0.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\google\code\gson\gson\2.2.2\gson-2.2.2.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl\2.9.0\lwjgl-2.9.0.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl_util\2.9.0\lwjgl_util-2.9.0.jar;C:\Users\l.michael\AppData\Roaming\.technic\modpacks\hosencorp-official\bin\modpack.jar;C:\Users\l.michael\AppData\Roaming\.technic\modpacks\hosencorp-official\bin\minecraft.jar net.minecraft.launchwrapper.Launch --username GommelLP --session token:8cb84732474840d4a36169b8fae0eacf:75eda1927f8c407095e4f9a5d18ddad9 --version 1.6.4-Forge9.11.1.965 --gameDir C:\Users\l.michael\AppData\Roaming\.technic\modpacks\hosencorp-official --assetsDir C:\Users\l.michael\AppData\Roaming\.technic\assets\virtual\legacy --tweakClass cpw.mods.fml.common.launcher.FMLTweaker --title Hosencorp --icon C:\Users\l.michael\AppData\Roaming\.technic\assets\packs\hosencorp-official\icon.png
[B#211] javaw.exe -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:MaxPermSize=256m -Djava.library.path=C:\Users\l.michael\AppData\Roaming\.technic\modpacks\hosencorp-official\bin\natives -Dfml.core.libraries.mirror=http://mirror.technicpack.net/Technic/lib/fml/%s -Dminecraft.applet.TargetDirectory=C:\Users\l.michael\AppData\Roaming\.technic\modpacks\hosencorp-official -cp C:\Users\l.michael\AppData\Roaming\.technic\cache\net\minecraft\launchwrapper\1.8\launchwrapper-1.8.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\ow2\asm\asm-all\4.1\asm-all-4.1.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\scala-lang\scala-library\2.10.2\scala-library-2.10.2.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\scala-lang\scala-compiler\2.10.2\scala-compiler-2.10.2.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\argo\argo\2.25_fixed\argo-2.25_fixed.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\bouncycastle\bcprov-jdk15on\1.47\bcprov-jdk15on-1.47.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\google\guava\guava\14.0\guava-14.0.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\com\google\code\gson\gson\2.2.2\gson-2.2.2.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl\2.9.0\lwjgl-2.9.0.jar;C:\Users\l.michael\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl_util\2.9.0\lwjgl_util-2.9.0.jar;C:\Users\l.michael\AppData\Roaming\.technic\modpacks\hosencorp-official\bin\modpack.jar;C:\Users\l.michael\AppData\Roaming\.technic\modpacks\hosencorp-official\bin\minecraft.jar net.minecraft.launchwrapper.Launch --username GommelLP --session token:8cb84732474840d4a36169b8fae0eacf:75eda1927f8c407095e4f9a5d18ddad9 --version 1.6.4-Forge9.11.1.965 --gameDir C:\Users\l.michael\AppData\Roaming\.technic\modpacks\hosencorp-official --assetsDir C:\Users\l.michael\AppData\Roaming\.technic\assets\virtual\legacy --tweakClass cpw.mods.fml.common.launcher.FMLTweaker --title Hosencorp --icon C:\Users\l.michael\AppData\Roaming\.technic\assets\packs\hosencorp-official\icon.png 
[B#211]  Jän 05, 2015 6:54:27 PM net.minecraft.launchwrapper.LogWrapper log
[B#211]  INFORMATION: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#211]  Jän 05, 2015 6:54:27 PM net.minecraft.launchwrapper.LogWrapper log
[B#211]  INFORMATION: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#211]  Jän 05, 2015 6:54:27 PM net.minecraft.launchwrapper.LogWrapper log
[B#211]  INFORMATION: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[B#211]  2015-01-05 18:54:27 [INFORMATION] [ForgeModLoader] Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
[B#211]  2015-01-05 18:54:27 [INFORMATION] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jdk1.8.0_25\jre
[B#211]  2015-01-05 18:54:27 [WARNUNG] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:27 [WARNUNG] [ForgeModLoader] The coremod worldcore.asm.WCFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:27 [WARNUNG] [ForgeModLoader] The coremod appeng.transformer.AppEngCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:27 [INFORMATION] [ForgeModLoader] [AppEng] Core Init
[B#211]  2015-01-05 18:54:27 [SCHWERWIEGEND] [ForgeModLoader] Coremod AsieLibCoremod: Unable to class load the plugin pl.asie.lib.core.AsieLibCoremod
[B#211]  java.lang.ClassNotFoundException: pl.asie.lib.core.AsieLibCoremod
[B#211]  	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[B#211]  	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[B#211]  	at java.security.AccessController.doPrivileged(Native Method)
[B#211]  	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[B#211]  	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:113)
[B#211]  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[B#211]  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[B#211]  	at java.lang.Class.forName0(Native Method)
[B#211]  	at java.lang.Class.forName(Class.java:344)
[B#211]  	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:386)
[B#211]  	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310)
[B#211]  	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:212)
[B#211]  	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[B#211]  	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[B#211]  	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[B#211]  	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:124)
[B#211]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
[B#211]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
[B#211]  2015-01-05 18:54:27 [WARNUNG] [ForgeModLoader] The coremod biomesoplenty.asm.BOPFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [INFORMATION] [STDERR] Warning: version of ForgeMultipart-universal-1.6.4-, 1.0.1.268 is newer than request 1.0.0.244
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod atomicstryker.dynamiclights.common.DLFMLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod mcp.mobius.evoc.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod logisticspipes.asm.LogisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod mcp.mobius.mobiuscore.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod openmods.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod mrtjp.projectred.compatibility.CompatibilityCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod resonant.core.ResonantPluginLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod tconstruct.preloader.TConstructLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [INFORMATION] [TCon-Preloader] Scalpel. Suction. Lumber axe. CLEAR! *zap*
[B#211]  2015-01-05 18:54:28 [INFORMATION] [TCon-Preloader] Constructing preloader (Modules: [tconstruct.preloader.AccessTransformers, tconstruct.preloader.ASMInterfaceRepair])
[B#211]  2015-01-05 18:54:28 [INFORMATION] [TCon-Preloader] Found a properties file. Attempting load...
[B#211]  2015-01-05 18:54:28 [INFORMATION] [TCon-Preloader] Loaded properties successfully. Using specified settings.
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod universalelectricity.core.UELoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [WARNUNG] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#211]  2015-01-05 18:54:28 [INFORMATION] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[B#211]  2015-01-05 18:54:28 [INFORMATION] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[B#211]  2015-01-05 18:54:28 [INFORMATION] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[B#211]  2015-01-05 18:54:28 [SCHWERWIEGEND] [ForgeModLoader] Unable to launch
[B#211]  java.util.ConcurrentModificationException
[B#211]  	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
[B#211]  	at java.util.ArrayList$Itr.remove(ArrayList.java:865)
[B#211]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
[B#211]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
[B#211]  Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[B#211] Analytics Response [runModpack]: 200

**Comment by gamedown0091** [comment]
da hat sich java 8 bei mir eingeschlichen sorry
